### ISSUE TITLE
Not working in .NET core 3.1

### ISSUE THREAD

**Issue by woeterman94** [Vereyon/FlashMessage#16]
Configured everything as described in the documentation. Messages are not showing. 

Works when using

```
_flashMessage.Confirmation("blabla");
return view();
```

but not when using
```
_flashMessage.Confirmation("blabla");
return RedirectToAction("Detail","Customer",new {customerId = 2});

```

**Comment by riverahugo** [comment]
I have the same problem, :( Any solution?

**Comment by cakkermans** [comment]
Are you running ASP.NET Core 3.1? I just tried this myself to investigate and I am also getting an unhandled exception about the `DefaultTempDataSerializer `not being able to serialize `byte[].`

That may also explain why it is working without the redirect, because you are not relying on the cookies then.

@woeterman94 and @riverahugo, can you check your log files / console output for any errors when using the `RedirectToAction()`?

I'll look into adjusting the serialization format if that alleviates the problems.

**Comment by riverahugo** [comment]
@cakkermans so
cookies can cause problems with flash Message? mainly in the RedirectToAction ??

**Comment by riverahugo** [comment]
@cakkermans 
you could solve it?

**Comment by riverahugo** [comment]
when i make a post and then RedirectToAction it gives me this error

InvalidOperationException: The 'Microsoft.AspNetCore.Mvc.ViewFeatures.Infrastructure.DefaultTempDataSerializer' cannot serialize an object of type 'System.Byte[]'.
for this error I Use
Install-Package Microsoft.AspNetCore.Mvc.NewtonsoftJson -Version 3.0.0
 services.AddControllersWithViews().AddNewtonsoftJson();
but FlashMessage dont work

**Comment by riverahugo** [comment]
@woeterman94 
I could already solve it, you have to check each services in your startup
remove unnecessary services and see which prevents flashMessage from working before redirectToAction

**Comment by cakkermans** [comment]
So it seems that the root cause is that since .NET Core 3 a different serializer for the `TempData `was implemented by Microsoft: [DefaultTempDataSerializer](https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.ViewFeatures/src/Infrastructure/DefaultTempDataSerializer.cs), which probably is using the new [System.Text.Json](url) serializer.

This serializer explicitly only supports some basic data types, `byte[]` is not one of them. Microsoft offers a way to use the NewtonsoftJson serializer. Install the package:

`Install-Package Microsoft.AspNetCore.Mvc.NewtonsoftJson -Version 3.0.0`

Then make sure to add a call to `AddNewtonsoftJson()` in your service configuration method:

```
// Old style ASP .NET Core
services.AddMvc().AddNewtonsoftJson();

// ASP .NET Core 3+ style
services.AddControllers().AddNewtonsoftJson();
services.AddControllersWithViews().AddNewtonsoftJson();
services.AddRazorPages().AddNewtonsoftJson();
```

Details can be found at: https://dotnetcoretutorials.com/2019/12/19/using-newtonsoft-json-in-net-core-3-projects/ The part of adding a call to `AddNewtonsoftJson()` was missing in #12

I'll make sure this starts working out of the box soon.

**Comment by riverahugo** [comment]
@cakkermans yes, that is correct, we need to add that package

**Comment by cakkermans** [comment]
@riverahugo, @woeterman94, I have largely re-implemented the library to work using the System.Text.Json serializer and using a tag helper instead of a HTML helper.

You can try it out using [Vereyon.Web.FlashMessage 2.0.0-beta2](https://www.nuget.org/packages/Vereyon.Web.FlashMessage/2.0.0-beta2)
Preliminary documentation can be found at: https://github.com/Vereyon/FlashMessage/blob/feature/tag-helper-json-serialization/README.md

**Comment by cakkermans** [comment]
I published FlashMessage 2.0.0 which resolved this issue.

**Comment by prinkpan** [comment]
I am still facing this problem even after installing v2.0.0 in my asp.net core 3.1 project.
